# Generated by Django 3.2.7 on 2021-09-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagedetails',
            name='offerValidity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpagedetails',
            name='url_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
