# Generated by Django 3.2.7 on 2021-09-28 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_landingpagedetails_offervalidity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpagedetails',
            name='offerTime',
        ),
    ]
